input_table: file_table-annotations.csv
file_tab_meta: file_table-metadata.csv

dir_metadata: resources/metadata_NPacGC_v2
dir_tarnames: resources/tar_names
dir_norm: resources/normalization_factors
dir_kallisto_names: resources/batch_meta_kallisto_names
# input_table: file_table.test.csv
dir_out: results
XDG_DATA_HOME: /scratch/bgrodner/Resources  # Dir to write the ncbitaxa database (written into 'ete' added to path)
                # Leave empty to indicate the current execution directory 
path_repository: workflow
dir_scripts: workflow/scripts

path_tarnames: .

batches_to_run: [
  # 'g1-st-am-ns',
  'g1-st-am-pa',
  # 'g2-st-am-ns',
  'g2-st-am-pa',
  # 'g3-uw-am-ns',
  'g3-uw-am-pa',
  'g3-uw-pm-pa',
  'g3-diel-pa',
  # 'd1-st-pa',
]

keys_kallisto: 
  join: target_id
  counts: est_counts

dict_batch_exps:
  'g2-st-am-pa': ['g2-ctd-pa','g2-inc-pa']
  'g2-st-am-ns': ['g2-ctd-ns','g2-inc-ns']

split_count_dir: data/split_count_files

keys_kofam:
  col_6tr: target_id_6tr_kofam

keys_diamond: 
  join: target_id
  taxid: taxid
  col_6tr: target_id_6tr_diamond
  cols: ['target_id','taxid','eval_taxid'] # assign cols to diamond,
  col_eval: eval_taxid
  col_taxid: taxid

cols_lin: [
  'domain',
  'kingdom',
  'phylum',
  'class',
  'order',
  'family',
  'genus',
  'species'
]

dict_gene_fnhmm:
  FBP1: /scratch/bgrodner/fbp1_paper/small_tree/results/hmmsearch/fbp1_hmmsearch_T30.tbl
  ISIP1: /scratch/bgrodner/metaT_data/isip_hmmsearch/results/hmmsearch/isip1_hmmsearch_T30.tbl
  ISIP2: /scratch/bgrodner/metaT_data/isip_hmmsearch/results/hmmsearch/isip2_hmmsearch_T30.tbl
  ISIP3: /scratch/bgrodner/metaT_data/isip_hmmsearch/results/hmmsearch/isip3_hmmsearch_T30.tbl
# keys_kofamscan: 
#   join: aa_id
#   to_enum: ['KO']
#   others_to_keep: ['score']
# cols_kofamscan: [
#   "","X","target_id","KO","thrshld","score","E-value","KO_definition"
# ] # must include 'target_id' and 'KO'


